modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="braincell" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Braincell" #mandatory
updateJSONURL="http://my.issue.tracker/" #optional
displayURL="http://my.issue.tracker/" #optional
logoFile="braincell_logo.png" #optional
credits="God." #optional
authors="BottomTextDanny, Peeko, Plummet Studios, Yosh, Coda." #optional
description='''
A community mod.
'''
[[dependencies.commune]] #optional
    modId="geckolib3" #mandatory
    mandatory=true #mandatory
    versionRange="[3.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.commune]] #optional
    modId="braincell" #mandatory
    mandatory=true #mandatory
    versionRange="[1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.commune]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.commune]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"